### ISSUE TITLE
Get data from the LabJack into a CSV file

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/geldaq#9]
To-do:

- [x] Get voltage readings
- [x] Put these readings into a Pandas dataframe
- [x] Write this dataframe to a file
- [x] Add column for real time in (PST)

**Comment by asennain** [comment]
All tasks have been completed except for writing the dataframe to a .csv file, which will be done promptly. A directory will also be created on the user's computer to consolidate recorded data to one location.

**Comment by blakeNaccarato** [comment]
@asennain that's great. On the subject of defining a default data directory, I think that's a good idea. I've wrestled with configuration and directories often enough to figure out a pretty good solution for the general problem of "deciding where stuff goes". If you do something like the following, we can incrementally buff it up as needed and make it proper configurable.

- [ ] Create the file `src/geldaq/configs.py`
- [ ] In this file, do `from pathlib import Path`
- [ ] Define a constant like so, `DEFAULT_DATA_DIR = Path("~/.geldaq/data").expanduser()
- [ ] Ensure it gets created like `DEFAULT_DATA_DIR.mkdir(exist_ok=True)`

Now, anywhere else in the project, even in other files, you should be able to say `from geldaq.configs import DEFAULT_DATA_DIR` and you can reuse that folder whenever you need to put a data file there.

You could use it like so:

```Python
df.to_csv(DEFAULT_DATA_DIR / data_filename)
```

where `data_filename` is probably the ISO time string of the current date and time you took the data. Also the "division" symbol here is pretty cool, it's actually being used to add another part to the existing path! Play around with `pathlib.Path` objects to see what I mean. They really are quite intuitive once you get the hang of it.

Remember your `py` Google Chrome shortcut? Use that to look into the `datetime` module, specifically how to take a datetime and convert it to an ISO standard string, which would be a good filename.

As `geldaq` develops, we can get a bit more fancy with the `configs` module, but for now it will be useful to get the hang of creating module constants and importing them elsewhere.

**Comment by asennain** [comment]
All tasks have been completed.
